#!/bin/bash -e

: ${REF:="master"}
: ${DLMETHOD:="curl"}
: ${TMPPATH:="$(./mktempdir)"}

while getopts ":r:b:t:e:g" OPTION; do
  case $OPTION in
    g)
      DLMETHOD="git"
      ;;
    b|t)
      REF="$OPTARG"
      ;;
    r)
      REPO="$OPTARG"
      ;;
    e)
      DESTDIR="$OPTARG"
      ;;
    *)
      echo "github(): invalid option -$OPTION" >&2
      ;;
  esac
done

mkdir -p "${TMPPATH}/repos"

REMOTE="$(sed -Ee 's%^((git(@|://)|http(s|)://)github\.com(/|:)|)%https://github.com/%g' <<< "$REPO")"

case "$DLMETHOD" in
  archive|curl)
    REMOTE="$(sed -Ee "s%(\.git|)$%/archive/${REF}.tar.gz%g" <<< "$REMOTE")"

    echo "Downloading $REMOTE ($REF)"
    curl -#L "$REMOTE" "$EXTRACT" | tar xzpf - -C "${TMPPATH}/repos"
    ;;
  git)
    git clone -b "$REF" "$REMOTE" "${DESTDIR}/$(basename $REMOTE)"
    ;;
esac

REPO= ; REF= ; EXTRACT= ; REMOTE= ; DLMETHOD= ;
unset REPO REF EXTRACT REMOTE DLMETHOD
exit 0
