#!/bin/bash

: ${REF:="master"}
: ${DESTDIR:="/tmp/bunsenlabs"}
: ${DLMETHOD:="curl"}

while getopts ":r:b:t:e:g" opt; do
  case $opt in
    g)
      DLMETHOD="git"
      ;;
    b|t)
      REF="$OPTARG"
      ;;
    r)
      REPO="$OPTARG"
      ;;
    e)
      DESTDIR="$OPTARG"
      ;;
    *)
      echo "github(): invalid option -$opt" >&2
      ;;
  esac
done

mkdir -p $DESTDIR

REMOTE="$(sed -Ee 's%^((git(@|://)|http(s|)://)github\.com(/|:)|)%https://github.com/%g' <<< "$REPO")"

case $DLMETHOD in
  archive|curl)
    REMOTE="$(sed -Ee "s%(\.git|)$%/archive/${REF}.tar.gz%g" <<< "$REMOTE")"

    echo "Downloading $REMOTE ($REF)"
    curl -#L $REMOTE $EXTRACT | tar xzpf - -C $DESTDIR
    ;;
  git)
    git clone -b $REF $REMOTE $DESTDIR/$(basename $REMOTE)
    ;;
esac

REPO= ; REF= ; EXTRACT= ; REMOTE= ; DESTDIR= ; DLMETHOD= ;
unset REPO REF EXTRACT REMOTE DESTDIR DLMETHOD
exit 0
